<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\build\Junevy.Communication.Common.props" />

  <ItemGroup>
    <ProjectReference Include="..\Junevy.Communication.Core\Junevy.Communication.Core.csproj" />
    <PackageReference Include="System.IO.Pipelines" Version="8.0.0" />
    <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Junevy.Communication.Channels.Tests" />
  </ItemGroup>

</Project>
